name: Daily iOS Ideas from Reddit

on:
  schedule:
    # Run daily at 09:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read
  issues: write

jobs:
  find-ideas:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Show Python environment
      run: |
        python --version
        pip --version
        uname -a

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate required secrets
      run: |
        python - << 'PY'
        import os, sys
        required = [
          'REDDIT_CLIENT_ID','REDDIT_CLIENT_SECRET','OPENAI_API_KEY',
          'EMAIL_SENDER','EMAIL_PASSWORD','EMAIL_RECEIVER'
        ]
        missing = [k for k in required if not os.getenv(k)]
        if missing:
            print('Missing required environment variables:', ', '.join(missing))
            sys.exit(1)
        else:
            print('All required secrets are present.')
        PY
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    - name: Run Reddit Idea Finder
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python reddit_idea_finder.py
        
    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v6
      continue-on-error: true
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Daily Ideas Workflow Failed',
            body: 'The daily Reddit idea finder workflow failed. Please check the logs.',
            labels: ['bug', 'automation']
          })
